version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    labels:
      - finance-tracker
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    labels:
      - finance-tracker
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 2; done; ./finance_tracker'
    links:
      - "db:db"
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web
  #   links:
  #     - "app:app"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app
  #   environment:
  #     - "REACT_APP_API_URL=http://localhost:8080"